### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by jouni** [saneef/eleventy-plugin-asciidoc#1]
Would it be possible to add syntax highlighting support for source code blocks? 

So that, for example, the following AsciiDoc source would be nicely highlighted in the output:

```asciidoc
[source,html]
----
<body>
  <p>This is some HTML</p>
</body>
----
```

**Comment by saneef** [comment]
AsciiDoc will convert above snippet to:

```html
<pre class="highlight"><code class="language-html" data-lang="html">&lt;body&gt;
  &lt;p&gt;This is some HTML&lt;/p&gt;
  &lt;/body&gt;</code></pre>
```

You'll have to use [Eleventy syntax highlight plugin](https://www.11ty.dev/docs/plugins/syntaxhighlight/) to highlight syntax.

**Comment by jouni** [comment]
I did try that, but for some reason the HTML is unchanged in the output. The syntax highlight plugin doesn't seem to process it. But I assume it should work, so I’ll give it another go. Quite new to 11ty in general, so I might have missed something obvious.

Thanks in any case for the nice AsciiDoc plugin!

**Comment by saneef** [comment]
My bad, Eleventy syntax highlight plugin doesn't solve the problem. 

Here in this [sample project](https://github.com/saneef/eleventy-plugin-asciidoc-tester/commit/9d1472f49f476437c9d1403b5ca0d7c488727f59) I have used [highlight.js](highlightjs.org/) to highlight code on the front end.

**Comment by jouni** [comment]
Right, so that does the highlighting on the client side. Thanks again!
