### ISSUE TITLE
Pre-process AsciiDoc files with another converter

### ISSUE THREAD

**Issue by xavier-calland** [saneef/eleventy-plugin-asciidoc#12]
When using [Markdown](https://www.11ty.dev/docs/linguals/markdown/), Markdown files are preprocessed (by default by Liquid).

This allows access to the `data` transmitted by Eleventy in the Markdown page.

It would be great to have this feature with AsciiDoc.

That said, I don't know if it's easy to retrieve the template engines configured in Eleventy.

**Comment by saneef** [comment]
@xavier-calland I'm sorry for the delayed reply.

I understand your use case. But, I could not find a clean way to like it is done with Markdown in Eleventy. I'll stick with the way the plugin works for now. 

I hope with Eleventy v3.0, there may be a better plugin system for templating engines. (See [11ty/eleventy/#1955038524](https://github.com/11ty/eleventy/pull/3074#issue-1955038524)).

I recommend you to keep a fork, with the changes you had suggest in #13.
