### ISSUE TITLE
`asciidocAttributes` isn't on `page`, but directly accessible through the name

### ISSUE THREAD

**Issue by nc7s** [saneef/eleventy-plugin-asciidoc#4]
It's me again lol

As of 11ty 1.0.1, `asciidocAttributes` is written directly onto `data`, thus accessible through `asciidocAttributes` in templates, and no more `page.asciidocAttributes`.

Btw, since it's a rather "breaking" change, how about changing it to a shorter name, like "adocAttrs"?

**Comment by saneef** [comment]
Thanks for pointing it out. I have updated the readme.

I'll stick with `asciidocAttributes` since I'm not making any changes in code. Also, I'm leaning towards clarity over brevity

**Comment by saneef** [comment]
If you prefer to access `asciidocAttributes` as `adocAttrs`, you can expose it through [eleventyComputed.js](https://www.11ty.dev/docs/data-computed/).

Create a global data file, `_data/eleventyComputed.js` and add these lines:
```js
module.exports = {
  adocAttrs: (data) => data.asciidocAttributes,
};
```

Now, you should be able to access the attributes using `adocAttrs` in templates. 😉

**Comment by nc7s** [comment]
It's just a bit long, but nowadays everyone's got autocomplete anyway 🌚
