### ISSUE TITLE
Relative includes

### ISSUE THREAD

**Issue by NIFR91** [saneef/eleventy-plugin-asciidoc#6]
I expected that an included file was relative to the current document. 

```adoc
----
include::an-included-file.txt[]
----
```
but the `:docdir:` attribute is set to the root of the project, perhaps an option to changed it for each document can be added.

**Comment by saneef** [comment]
Thanks for pointing that out. Will look into it.

**Comment by saneef** [comment]
The relative paths should work in the newly released v2.0.0 version.

**Comment by NIFR91** [comment]
I can confirm the includes are working,  

Thank you for such quick change and your work in this plugin.
