### ISSUE TITLE
Support for Mermaid and Asciidoctor diagrams

### ISSUE THREAD

**Issue by DonClysdale** [saneef/eleventy-plugin-asciidoc#8]
It would be really nice to support Mermaid and asciidoctor diagrams in asciidoc pages, like mermaid diagrams are supported in eleventy for markdown pages.

**Comment by saneef** [comment]
The official [Asciidoctor Diagram](https://docs.asciidoctor.org/diagram-extension/latest/) doesn't support Node.js. So, I don't plan to support for diagrams like Mermaid by default.

Having said that, I'll see whether it is possible to support Mermaid diagrams like I did for [build time syntax highlighting for Asciidocs](https://saneef.com/tutorials/asciidoc-syntax-highlighting/#2.-build-time-transformation).

**Comment by saneef** [comment]
@DonClysdale I checked the feasibility of rendering Mermaid.js diagrams on build side. Unfortunately, Mermaid.js only renders the charts within a browser. The approaches out there are using headless browsers to render the charts. It is out of the scope of this plugin.

I recommend using a literal or code block of AsciiDoc to write Mermaid code, and use [client-side rendering](https://mermaid.js.org/config/usage.html).

**Comment by saneef** [comment]
Here, https://github.com/saneef/eleventy-plugin-asciidoc-tester/commit/10414eede83f215aed3aef8ee2c0c13883f28f23, is how I set up client-side rendering of Mermaid.js with AsciiDoc.
