### ISSUE TITLE
Update dependency : @asciidoctor/core 3.0.2

### ISSUE THREAD

**Issue by xavier-calland** [saneef/eleventy-plugin-asciidoc#9]
Latest version of asciidoctor.js is 3.0.2.
It would be great to have the latest version in this plugin.

A switch from [asciidoctor](https://www.npmjs.com/package/asciidoctor) to [@asciidoctor/core](https://www.npmjs.com/package/@asciidoctor/core) can be a good idea as "asciidoctor" is juste an export from "'@asciidoctor/core'" `module.exports = require('@asciidoctor/core')`

**Comment by saneef** [comment]
Thanks, @xavier-calland. 

I'll make those changes and create a release soon.

**Comment by saneef** [comment]
Released new version v3.0.1
